#include "modules/register_module_types.h"

void initialize_clockmakers_framework_module(ModuleInitializationLevel p_level);
void uninitialize_clockmakers_framework_module(ModuleInitializationLevel p_level);
